{% target '/etc/nullunit.conf' %}# this file is auto generated by config-curator do not edit by hand
# generated at {{ __timestamp__ }}
# for {{ _hostname }}, id: {{ _structure_id }}, uuid: {{ __uuid__ }}

[mcp]
host: {{ mcp_host }}
proxy: {{ mcp_proxy }}
job_id: {{ mcp_job_id }}
instance_id: {{ mcp_instance_id }}
build_name: {{ mcp_build_name }}
project_name: {{ mcp_project_name }}
commit_version: {{ mcp_commit_version }}
promotion_tag: {{ mcp_promotion_tag }}
instance_cookie: {{ mcp_instance_cookie }}
resource_name: {{ mcp_resource_name }}
resource_index: {{ mcp_resource_index }}
store_packages: {{ mcp_store_packages }}
structure_id: {{ _structure_id }}

[misc]
proxy_env_var: {{ mcp_proxy_env_var }}

[git]
url: {{ mcp_git_url }}
branch: {{ mcp_git_branch }}
proxy: {{ mcp_git_proxy }}

[make]
target: {{ mcp_make_target }}

[packrat]
host: {{ packrat_host }}
proxy: {{ packrat_proxy }}
username: {{ nullunit_packrat_username }}
password: {{ nullunit_packrat_password }}

[confluence]
host: {{ confluence_host }}
proxy: {{ confluence_proxy }}
username: {{ nullunit_confluence_username }}
password: {{ nullunit_confluence_password }}
{% endtarget %}
